name: DEV CI - Full Suite Tests

on:
    push:
        branches: ['dev', 'qa', 'qa_*', 'qa-*', 'v*', 'feature/**']
    pull_request:
        branches: ['dev', 'qa', 'qa_*', 'qa-*', 'v*', 'feature/**']

jobs:
    unit-tests:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - uses: actions/setup-node@v4
              with:
                node-version: 20
            - name: Install dependencies
              run: npm install
              working-directory: ./my-app
            - run: npx vitest run
    
    e2e-playwright:
        runs-on: ubuntu-latest
        env:
            SAUCE_USERNAME: ${{ secrets.SAUCE_USERNAME }}
            SAUCE_ACCESS_KEY: ${{ secrets.SAUCE_ACCESS_KEY }}
        steps:
            - uses: actions/checkout@v4
            - uses: actions/setup-node@v4
              with:
                node-version: 20
            - run: npm install
            - run: npx playwright install
            - name: Run Playwright tests on Sauce Labs
              run: npx playwright test --project=firefox
              working-directory: ./my-app
