name: Deploy to GitHub Pages

on:
  push:
    branches:
      - 'main'
      - 'releases/**'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 24

      - name: Install dependencies
        run: npm install
        working-directory: ./my-app

      - name: Clean old build
        run: rm -rf dist
        working-directory: ./my-app        

      - name: Build site
        run: npm run build
        working-directory: ./my-app

      - name: Copy index.html to 404.html
        run: cp dist/index.html dist/404.html
        working-directory: ./my-app

      - name: Deploy to GitHub Pages
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          npx gh-pages -d dist \
          -r "https://x-access-token:${GITHUB_TOKEN}@github.com/drocpdp/davidreynon_react.git"
        working-directory: ./my-app
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

