name: Deploy to GitHub Pages

on:
  push:
    branches: [main]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install
        working-directory: ./my-app

      - name: Build site
        run: npm run build
        working-directory: ./my-app

      - name: Deploy to GitHub Pages
        run: npm run deploy
        working-directory: ./my-app
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
